### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by omnikeycard** [py-mine/mcstatus#370] opened 2022-08-08 18:54 UTC
Hello. Today, the bot that collected statistics about online from the server suddenly stopped working. When calling the `server.status()` function, the error [Errno 32] Broken pipe appears. What could be the problem?

**Comment by kevinkjt2000** [comment] 2022-08-08 19:16
Broken pipe could be any number of exceptional behaviors, and it is just that, exceptional. Seems like try-except was forgotten in to catch possible exceptions. Was the server offline or was there a loss of connection for a moment? Do you have code to showcase? Is there try-except around `server.status()` in this code?

**Comment by omnikeycard** [comment] 2022-08-08 19:41
This is my code

```
server = JavaServer.lookup(cfg.server_ip)
attempt_number = 0
while True:
    try:
        status = server.status()
        online = str(status.players.online)
        max_online = str(status.players.max)
        await bot.change_presence(status=discord.Status.online, activity=discord.Game(online+"/"+max_online)) # Saving the result
        attempt_number = 0
    except:
        await bot.change_presence(status=discord.Status.online, activity=discord.Game("???/60"))
        if attempt_number < cfg.number_of_attempts:
            attempt_number += 1
        else:
            break
```

**Comment by omnikeycard** [comment] 2022-08-08 19:43
> Broken pipe could be any number of exceptional behaviors, and it is just that, exceptional. Seems like try-except was forgotten to catch possible exceptions. Was the server offline or was there a loss of connection for a moment? Do you have code to showcase? Is there try-except around `server.status()` in this code?

I restarted the server in Minecraft and restarted the bot itself, it didn't work

**Comment by ItsDrike** [comment] 2022-08-08 21:34
After further discussion on discord, starting [here](https://discord.com/channels/936788458939224094/938591600160956446/1006304515756150855), it turns out that this problem is being caused by the server not being able to respond to `test_ping` request, even though requesting status alone works.

This was further confirmed by minecraft itself, not being able to show the latency level, and only showing (no connection):
![image](https://user-images.githubusercontent.com/20902250/183517631-0fb20744-2467-4e17-8ae4-7739aaeb7d75.png)

it's not yet clear whether this is some plugin messing with how the server responds to these ping requests, or whether this is the server implementation itself (in this case `Pufferfish core`) not being able to handle ping requests. For now, a quick solution to this would be to manually request the status without requesting ping:
```py
from mcstauts import JavaServer
from mcstauts.pinger import ServerPinger
from mcstauts.protocol.connection import TCPSocketConnection

s = JavaServer.lookup("65.108.107.110:33621")
conn = TCPSocketConnection(s.address, timeout=3)
pinger = ServerPinger(conn, address=s.address)
pinger.handshake()
status = pinger.read_status()
#status.latency = pinger.test_ping()  # This causes the Broken Pipe error
```
Note that since setting status.latency is omitted, it will be `None`.

We may want to consider automatically handling issues that occur in `test_ping`, so that we could at least provide the actual status response, even though it would be without `latency`. This may be a better solution than forcing people to use the code above, considering most of the functions and classes it references aren't a part of the publicly exposed API, and may change over time.

**Comment by kevinkjt2000** [comment] 2022-08-09 17:14
Duplicate of #316

**Closed by kevinkjt2000** 2022-08-09 17:14 UTC
Labels: type: bug, status: planning
