### ISSUE TITLE
[Errno 57] Socket is not connected

### ISSUE THREAD

**Issue by crypto-sami** [py-mine/mcstatus#543] opened 2023-05-14 11:19 UTC
Hello, when I run this piece of code to get the players online, it tells me the number of players online however throws out an error when I query to see which players are online. I have the port forwarding set up correctly and the server is ran on Debian 11 in a docker container.

<img width="738" alt="image" src="https://github.com/py-mine/mcstatus/assets/90721225/8cff7741-8663-48cf-95b6-ae78bb50371f">

<img width="747" alt="image" src="https://github.com/py-mine/mcstatus/assets/90721225/744cb99c-c173-4b6f-b6b4-511c74962525">

**Comment by PerchunPak** [comment] 2023-05-14 11:21
Can you provide all commands to reproduce?

**Comment by PerchunPak** [comment] 2023-05-14 11:23
Also, it would be greate if you could try this sample from https://github.com/py-mine/mcstatus/issues/538#issuecomment-1546726344.

**Comment by crypto-sami** [comment] 2023-05-14 11:30
hello i ran that and it returned an error, what do you mean all commands to reproduce? as in the whole error message?

File "c:\Users\Sami\Documents\VSCode Projects\python-ssh\main.py", line 4, in <module>
    server = mcstatus.lookup("mc.sturk.au:25565")
AttributeError: module 'mcstatus' has no attribute 'lookup'

**Comment by PerchunPak** [comment] 2023-05-14 11:31
Oh, my error. Updated the comment, try again.

> what do you mean all commands to reproduce?

How do you run the container?

**Comment by crypto-sami** [comment] 2023-05-14 11:33
i ran it now and it says both status and async status is ok however it said async query is not ok. Its just a paper mc server within a docker container, to run i just run a basic .sh file i set up

**Comment by PerchunPak** [comment] 2023-05-14 11:40
Nevermind, I reproduced it with `docker.io/library/python:3.11-slim`.

Run `mcstatus mc.sturk.au query > log.txt` command and send here unedited content of the `log.txt` file please.

**Comment by crypto-sami** [comment] 2023-05-14 12:33
this is what was put in the log.txt
The server did not respond to the query protocol.
Please ensure that the server has enable-query turned on, and that the necessary port (same as server-port unless query-port is set) is open in any firewall(s).
See https://wiki.vg/Query for further information.

**Comment by crypto-sami** [comment] 2023-05-14 14:03
i run the staff++ plugin, i dont think this should cause any issues. I also only have the port 22565 open on my router settings. I haven't set a certain query port in the server config properties

**Comment by ItsDrike** [comment] 2023-05-16 20:33
Yeah, this is probably just another query isn't enabled or accessible issue, but what surprises me is the error message. I'd expect the error on connection getting established, not on closing.

**Comment by kevinkjt2000** [comment] 2023-05-16 20:36
Well the error is that the socket was never connected. The exit methods attempt a losing a socket that was never connected.

**Comment by kevinkjt2000** [comment] 2023-05-16 20:39
Closing this as a duplicate of #489

**Closed by kevinkjt2000** 2023-05-16 20:39 UTC
Labels: meta: duplicate

**Comment by ItsDrike** [comment] 2023-05-16 20:47
Yes, but I wouldn't even expect it to make it past `__init__` on the `UDPSocketConnection` connection, since connection establishing would fail with an exception. It's weird that it's getting into __exit__, and attempting a close in the first place, as that would imply that the connection was somehow established, doesn't it?

https://github.com/py-mine/mcstatus/blob/0f66b5ca306ea0a4992533c89af6830348b69d80/mcstatus/server.py#L193

https://github.com/py-mine/mcstatus/blob/0f66b5ca306ea0a4992533c89af6830348b69d80/mcstatus/protocol/connection.py#L548

Although now that I'm thinking of it, UDP connections don't really do any sort of handshake, so I suppose it makes sense.

**Comment by PerchunPak** [comment] 2023-05-16 21:21
Sorry for such delay, just want to mention that I got `TimeoutError` when tested it. I think, just the screenshot in the head of the issue is not full.

**Comment by ItsDrike** [comment] 2023-05-16 21:25
Yeah, the screenshot not being complete makes a lot more sense actually, even though UDP would probably indeed let you get past `__init__` as there's no initial handshake, during query, you'd still need to actually send/receive traffic, and it's at that moment where the error would absolutely happen. But at that point, you're already within a context manager, and so `__exit__` will get ran even if there was an exception, triggering another exception encountered during close.
